
const data = [
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREwJR_uef5jkwUzLm6TvfI2pPGcVhkFWzVFl5bzlWjuw&s",
    title: "Fruit Gums",
    description: "This is the product description",
    prevPrice: "R100",
    newPrice: "50",
    company: "Mister Sweets",
    color: "white",
    category: "sweets",
  },
  {
    img: "https://www.mistersweet.co.za/images/default-source/products/marshmallows/yumallows-150g-p-and-w-bag.png?sfvrsn=55cb5058_2",
    title: "Yumallows",
    description: "This is the product description",
    prevPrice: "R200",
    newPrice: "100",
    company: "Mister Sweets",
    color: "white",
    category: "sweets",
  },

  {
    img: "https://www.mistersweet.co.za/images/default-source/products/gums-and-jellies/wine-gums-125g.png?sfvrsn=66968575_2",
    title: "Wine Gums",
    description: "This is the product description",
    prevPrice: "R400",
    newPrice: "200",
    company: "Mister Sweets",
    color: "white",
    category: "sweets",
  },
  {
    img: "https://www.mistersweet.co.za/images/default-source/default-album/ms_vampire-fangs_60g-bag.png?sfvrsn=32e648fa_4",
    title: "Vampire Fangs",
    description: "This is the product description",
    prevPrice: "R600",
    newPrice: "300",
    company: "Mister Sweets",
    color: "white",
    category: "sweets",
  },
  {
    img: "https://www.shoprite.co.za/medias/10701987EA-checkers515Wx515H?context=bWFzdGVyfGltYWdlc3wzMjg0MDR8aW1hZ2UvcG5nfGltYWdlcy9oYjIvaDBmLzg5NjQ3MjE1MDgzODIucG5nfDIxMDQyNTk2MjU4YWFhOGY1NGU0NzU4NGI2MDQ4MDNhZjQ5ZjQyNzdkMmZhMWI2OTM3ZGRhNWJlOWY4ZWFjMTI",
    title: "Speckled Eggs",
    description: "This is the product description",
    prevPrice: "R800",
    newPrice: "400",
    company: "Mister Sweets",
    color: "black",
    category: "sweets",
  },
  {
    img: "https://www.mistersweet.co.za/images/default-source/products/other-sweets/cherries-and-berries-twists-60g.png?sfvrsn=ade53da6_3",
    title: "Twists",
    description: "This is the product description",
    prevPrice: "R100",
    newPrice: "50",
    company: "Mister Sweets",
    color: "black",
    category: "sweets",
  },

  {
    img: "https://cdn-prd-02.pnp.co.za/sys-master/images/h16/h80/11187195740190/silo-product-image-v2-01Jun2023-181827-6001704009898-Straight_on-148388-3730_515Wx515H",
    title: "Glow Worms",
    description: "This is the product description",
    prevPrice: "R200",
    newPrice: "100",
    company: "Mister Sweets",
    color: "black",
    category: "sweets",
  },

  {
    img: "https://www.checkers.co.za/medias/10733260EA-checkers515Wx515H?context=bWFzdGVyfGltYWdlc3wzMzM1ODd8aW1hZ2UvcG5nfGltYWdlcy9oYmEvaGQwLzEwNTQ4ODU0Nzg0MDMwLnBuZ3xiZjBhZTRlNWFjYTI1YjcwYzZhZDNhYzc0YWE4YTBhOTQ5ZTdjMzEzNDFkNDNiYzhhYzk1YTVlMTJkNmRmMWRj",
    title: "Simba Beef",
    description: "This is the product description",
    prevPrice: "R150",
    newPrice: "100",
    company: "Simba",
    color: "black",
    category: "chips",
  },

  {
    img: "https://www.checkers.co.za/medias/10859947EA-checkers515Wx515H?context=bWFzdGVyfGltYWdlc3wyNTU0NzV8aW1hZ2UvcG5nfGltYWdlcy9oZjcvaDBkLzEwNTY1MjYwNTQxOTgyLnBuZ3xkN2NjM2FkYzk0NzkxNmJlYWFhOGU1YjFkZmM0ZjNhZDFmM2ZlZmRiOTJiNjM2YWNmNTZiMGEzMjk2NWE0OTlh",
    title: "Simba Steakhouse Beef",
    description: "This is the product description",
    prevPrice: "R150",
    newPrice: "50",
    company: "Simba",
    color: "red",
    category: "chips",
  },

  {
    img: "https://www.deeliver.co.za/cdn/shop/files/simba-chips-large-salt-vinegar.jpg?v=1686947862",
    title: "Simba Salt and Vinegar",
    description: "This is the product description",
    prevPrice: "R200",
    newPrice: "100",
    company: "Simba",
    color: "red",
    category: "chips",
  },
  {
    img: "https://www.checkers.co.za/medias/10733259EA-checkers515Wx515H?context=bWFzdGVyfGltYWdlc3wyODUxMTh8aW1hZ2UvcG5nfGltYWdlcy9oMzEvaGRmLzEwNTQ4ODUzMDgwMDk0LnBuZ3w5MDI0NzEyOWI5NDg3Mzk3ZjQ2N2E5MDhjZDIyOTk2MDE3ZjE2NzVjNDk0MzlhNTQwNmQyOTIwNTNlZGVhYzdj",
    title: "Simba Creamy Cheddar",
    description: "This is the product description",
    prevPrice: "R200",
    newPrice: "100",
    company: "Simba",
    color: "red",
    category: "chips",
  },
  {
    img: "https://auberginefoods.com/cdn/shop/products/pack-simba-mrs.-h.s.-ball_s-chutney_grande.png?v=1636564654",
    title: "Simba Mrs H.S Ball's",
    description: "This is the product description",
    prevPrice: "R220",
    newPrice: "150",
    company: "Simba",
    color: "red",
    category: "chips",
  },
  {
    img: "https://www.dischem.co.za/media/catalog/product/cache/41664faeeb094fcc68fc0c934ed2e5ae/5/d/5d66330384df9_6009510808513.jpg",
    title: "Simba Mexican Chilli",
    description: "This is the product description",
    prevPrice: "R240",
    newPrice: "150",
    company: "Simba",
    color: "yellow",
    category: "chips",
  },
  {
    img: "https://cdn-prd-02.pnp.co.za/sys-master/images/h33/hde/11241150677022/silo-product-image-v2-15Aug2023-180813-6009510809497-Straight_on-165103-736_515Wx515H",
    title: "Simba Cheese and Onion",
    description: "This is the product description",
    prevPrice: "R260",
    newPrice: "50",
    company: "Simba",
    color: "yellow",
    category: "chips",
  },

  {
    img: "https://www.checkers.co.za/medias/10398824EA-checkers515Wx515H?context=bWFzdGVyfGltYWdlc3wxNDI4MjR8aW1hZ2UvcG5nfGltYWdlcy9oMDEvaDAyLzEwMDQ5MjkyMzM3MTgyLnBuZ3wzODljZTM3NTI5N2ZmZTdjNjk4OTQ4Y2YyZTBlZDEwY2EwOTcxMTNlMGJmMGJlNWU2MmMzM2Q0ZjhhZTQ2ZTFh",
    title: "Cadbury Biscuit",
    description: "This is the product description",
    prevPrice: "R280",
    newPrice: "50",
    company: "Cadbury",
    color: "yellow",
    category: "chocolate",
  },
  {
    img: "https://www.checkers.co.za/medias/10240811EA-checkers300Wx300H?context=bWFzdGVyfGltYWdlc3w1NzgzM3xpbWFnZS9wbmd8aW1hZ2VzL2gzNC9oNjcvMTAwNDkyODE1ODkyNzgucG5nfDNjYmMyOWI3MDgyOGU0MmVhMTkzOWE3OTEwNmU0YmI2ZmM3NjIxMGUwOWNlNzRmMzJmZWVjOGUyMGUzNTY4ZTc",
    title: "Cadbury Whole Nut",
    description: "This is the product description",
    prevPrice: "R300",
    newPrice: "100",
    company: "Cadbury",
    color: "yellow",
    category: "chocolate",
  },
  {
    img: "https://m.media-amazon.com/images/I/71ctv5tIaFL._SL1500_.jpg",
    title: "Cadbury Milk",
    description: "This is the product description",
    prevPrice: "R320",
    newPrice: "200",
    company: "Cadbury",
    color: "green",
    category: "chocolate",
  },
  {
    img: "https://cdn.shopify.com/s/files/1/0629/2245/7274/products/cadbury-dairy-milk-crunchie-milk-chocolate-slab-80-g-620224.jpg?v=1669102299",
    title: "Cadbury Crunchie",
    description: "This is the product description",
    prevPrice: "R340",
    newPrice: "100",
    company: "Cadbury",
    color: "green",
    category: "chocolate",
  },
  {
    img: "https://www.coles.com.au/_next/image?url=https%3A%2F%2Fproductimages.coles.com.au%2Fproductimages%2F2%2F2351607.jpg&w=640&q=90",
    title: "Cadbury Top Deck",
    description: "This is the product description",
    prevPrice: "R360",
    newPrice: "50",
    company: "Cadbury",
    color: "green",
    category: "chocolate",
  },
  {
    img: "https://cdn.shopify.com/s/files/1/0722/7781/9666/products/cadbury-king-size-chocolate-block-dairy-milk-caramello.jpg?v=1677398820&width=533",
    title: "Cadbury Caramello",
    description: "This is the product description",
    prevPrice: "R380",
    newPrice: "150",
    company: "Cadbury",
    color: "green",
    category: "chocolate",
  },
  {
    img: "https://www.candydistrict.com/cdn/shop/products/cadbury-dairy-milk-oreo-bar-candy-district-online-candy-store.jpg?v=1572082904",
    title: "Cadbury Oreo",
    description: "This is the product description",
    prevPrice: "R400",
    newPrice: "200",
    company: "Cadbury",
    color: "blue",
    category: "chocolate",
  },
  {
    img: "https://assets.woolworthsstatic.co.za/Bakers-Original-Strawberry-Whirls-Biscuits-200-g-6001056633000.jpg?V=TEFr&h=600&o=eyJidWNrZXQiOiJ3dy1vbmxpbmUtaW1hZ2UtcmVzaXplIiwia2V5IjoiaW1hZ2VzL2VsYXN0aWNlcmEvcHJvZHVjdHMvaGVyby8yMDIyLTAyLTE4LzYwMDEwNTY2MzMwMDBfaGVyby5qcGcifQ&q=85&w=600",
    title: "Bakers Whirls",
    description: "This is the product description",
    prevPrice: "R420",
    newPrice: "210",
    company: "Bakers",
    color: "blue",
    category: "biscuits",
  },
  {
    img: "https://southafricansweets.com/cdn/shop/files/BAKERSChoc-KitsClassicBiscuits200g.png?v=1690961103",
    title: "Bakers ChocKits",
    description: "This is the product description",
    prevPrice: "R440",
    newPrice: "220",
    company: "Bakers",
    color: "blue",
    category: "biscuits",
  },

  {
    img: "https://auberginefoods.com/cdn/shop/products/crunchy_choc_512x512.jpg?v=1627786496",
    title: "Bakers Romany Creams",
    description: "This is the product description",
    prevPrice: "R460",
    newPrice: "230",
    company: "Bakers",
    color: "blue",
    category: "biscuits",
  },
  {
    img: "https://exclusivelyfood.co.za/wp-content/uploads/2020/03/BAKERS-MARIE-BISCUITS-200g.jpg",
    title: "Bakers Marie Biscuits",
    description: "This is the product description",
    prevPrice: "R480",
    newPrice: "240",
    company: "Bakers",
    color: "orange",
    category: "biscuits",
  },
  {
    img: "https://www.checkers.co.za/medias/10124117EAv2-checkers515Wx515H?context=bWFzdGVyfGltYWdlc3wxMjQzOTZ8aW1hZ2UvcG5nfGltYWdlcy9oMTUvaGNkLzk1OTE3NTUyNDM1NTAucG5nfDY1YjcxMzY4OTE4M2Y3ZTJmMGQ4YjY0ZmQ3YWM4ZjAyMWVmNzVkZWQ1NmE4NTgxMTc2ODc2MjMxMzljNDIyMmQ",
    title: "Bakers Tennis Biscuits",
    description: "This is the product description",
    prevPrice: "R500",
    newPrice: "250",
    company: "Bakers",
    color: "orange",
    category: "biscuits",
  },
  {
    img: "https://cdn-prd-02.pnp.co.za/sys-master/images/hfc/h6b/10983895629854/silo-product-image-v2-19Oct2022-180133-6001056486002-Straight_on-62634-427_400Wx400H",
    title: "Bakers Nuttikrust",
    description: "This is the product description",
    prevPrice: "R520",
    newPrice: "50",
    company: "Bakers",
    color: "orange",
    category: "biscuits",
  },
  {
    img: "https://www.shoprite.co.za/medias/10206181EAV2-checkers515Wx515H?context=bWFzdGVyfGltYWdlc3w5MjY5M3xpbWFnZS9wbmd8aW1hZ2VzL2gwNS9oNTgvOTU5MTc3ODI3OTQ1NC5wbmd8NjU1ZmQyMDdkZjk3OWRjZjhkMmRhZDNkZmYyYmI4NGQwZjcyZmM5Y2Q0YTBkYjM3MjEyNWZhNzg1MjM0YzFmZQ",
    title: "Bakers Topper",
    description: "This",
    prevPrice: "R540",
    newPrice: "270",
    company: "Bakers",
    color: "orange",
    category: "biscuits",
  },
];

export default data;
